### ISSUE TITLE
[discussion] add this package to AUR

### ISSUE THREAD

**Issue by nandgator** [totoro-ghost/sddm-astronaut#2]
Would you mind adding this package to [AUR](https://aur.archlinux.org/)?

I have a [Plymouth theme](https://aur.archlinux.org/packages/plymouth-theme-aregression/). If you're busy I wouldn't mind adding [`sddm-astronaut`](https://github.com/totoro-ghost/sddm-astronaut/) to AUR.

**Comment by totoro-ghost** [comment]
Thanks for the pull request. If you like you can add this to AUR.

**Comment by RaZ0rr-Two** [comment]
Sorry for bumping this but are there any updates?

**Comment by nandgator** [comment]
There you go https://aur.archlinux.org/packages/sddm-theme-astronaut/
