### ISSUE TITLE
Use a colour instead of an image

### ISSUE THREAD

**Issue by kamack38** [totoro-ghost/sddm-astronaut#5]
Can't the card background image be replaced by a solid colour?
```
Rectangle
{
	//Image background for input forms
	anchors.fill: parent
	color: "#00050e"
}
```

**Comment by kamack38** [comment]
This also fixes the issue with higher resolution displays where the card image doesn't cover the whole rectangle.

**Comment by totoro-ghost** [comment]
Thanks for the fix.
